version: '3.7'
services:
  postgres:
    container_name: postgresql
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview-telkom
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
  api:
    container_name: backend_api
    build: .
    ports: 
      - '8000:8000'
    environment:
      - APP_PORT=8000
      - DATABASE_HOST=postgresql
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=interview-telkom
      - DATABASE_PORT=5432
